# Generated by Django 4.2.8 on 2024-02-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_user_subscriptioncancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='companyname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postalcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscriptionid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='word_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='word_number',
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
