# Generated by Django 4.2.2 on 2024-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='user',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
